### ISSUE TITLE
Please Remove 'People also viewed' and 'Today's news and views'

### ISSUE THREAD

**Issue by Meshugah** [lucboruta/linkedin-feed-blocker#3]
'[Today's news and views](https://imgur.com/QK7BolL)' appears on the right side of the 'My Network' page.

'[People also viewed](https://imgur.com/TxTi9bK)' appears on the right side of the Profile page

Thanks. This is a big step up on making LinkedIn usable.

**Comment by lucboruta** [comment]
I've merged @viktornonov's PR https://github.com/lucboruta/linkedin-feed-blocker/pull/2, and the updated extension is now pending review on the Chrome Web Store.

**Comment by lucboruta** [comment]
This extension is no longer maintained. Please consider using @njelich's [LinkOff](https://github.com/njelich/linkoff) instead.
