### ISSUE TITLE
Post page is also hidden

### ISSUE THREAD

**Issue by leodavesne** [lucboruta/linkedin-feed-blocker#4]
I really like this extension, thank you for this!!

I'm happy to not see the feed, but I still want to be able to read the isolated posts, as I can navigate from the notifications to the post page, while not being tempted by reading the feed afterwards.

**Comment by lucboruta** [comment]
This extension is no longer maintained. Please consider using @njelich's [LinkOff](https://github.com/njelich/linkoff) instead.
