### ISSUE TITLE
Top Stories

### ISSUE THREAD

**Issue by laxiyo** [lucboruta/linkedin-feed-blocker#5]
![image](https://user-images.githubusercontent.com/8433481/101270734-f0fa2e00-3749-11eb-9f3c-e8010152b671.png)

Can you guys please remove the three seconds I screenshotted that appear on the right side of the home page?

Thank you!!!

**Comment by lucboruta** [comment]
I've received other requests to block elements from the sidebar to the right. I might just try to block all elements in that sidebar altogether.

**Comment by laxiyo** [comment]
That would be amazing! Love it otherwise.

**Comment by lucboruta** [comment]
This extension is no longer maintained. Please consider using @njelich's [LinkOff](https://github.com/njelich/linkoff) instead.
