### ISSUE TITLE
Block "Linkedin News"

### ISSUE THREAD

**Issue by hologram9014** [lucboruta/linkedin-feed-blocker#8]
<img width="960" alt="Screen Shot 2021-03-27 at 1 08 49 PM" src="https://user-images.githubusercontent.com/81489234/112733538-cb15b680-8efd-11eb-9b31-0c0fae38774a.png">

**Comment by lucboruta** [comment]
This extension is no longer maintained. Please consider using @njelich's [LinkOff](https://github.com/njelich/linkoff) instead.
